import { IPayment, IWithdraw } from '@/types/payment'

export const PaymentsData: IPayment[] = [
  {
    sl: 1,
    paymentID: '045HJ',
    ProjectName: 'Web dev',
    paymentType: 'Bank Wallet',
    accountName: 'Indian Bank',
    accountNumber: '46669496496',
    transactionId: '005002',
    payAmount: '110 USD',
    paymentDay: '03-02-2025',
    status: 'spam',
    id: 'P0001',
    paymentMethod: 'SBI Bank',
    acocuntHolderName: '',
    transactionReceipt: '',
    additionalNote: '',
    Currency: '',
    Name: ''
  },
  {
    sl: 2,
    paymentID: '045HJ',
    ProjectName: 'App dev',
    paymentType: 'Bank',
    accountName: 'Indian Bank',
    accountNumber: '46669496496',
    transactionId: '005002',
    payAmount: '110 USD',
    paymentDay: '03-02-2025',
    status: 'pending',
    id: 'P0001',
    paymentMethod: 'SBI Bank',
    acocuntHolderName: '',
    transactionReceipt: '',
    additionalNote: '',
    Currency: '',
    Name: ''
  },
  {
    sl: 3,
    paymentID: '045HJ',
    ProjectName: 'App dev',
    paymentType: 'Bank',
    accountName: 'Indian Bank',
    accountNumber: '46669496496',
    transactionId: '005002',
    payAmount: '110 USD',
    paymentDay: '03-02-2025',
    status: 'accepted',
    id: 'P0001',
    paymentMethod: 'Paypal',
    acocuntHolderName: '',
    transactionReceipt: '',
    additionalNote: '',
    Currency: '',
    Name: ''
  },
  {
    sl: 4,
    paymentID: '045HJ',
    ProjectName: 'App dev',
    paymentType: 'Bank',
    accountName: 'Indian Bank',
    accountNumber: '46669496496',
    transactionId: '005002',
    payAmount: '110 USD',
    paymentDay: '03-02-2025',
    status: 'pending',
    id: 'P0001',
    paymentMethod: 'US Bank',
    acocuntHolderName: '',
    transactionReceipt: '',
    additionalNote: '',
    Currency: '',
    Name: ''
  },
  {
    sl: 5,
    paymentID: '045HJ',
    ProjectName: 'App dev',
    paymentType: 'Bank wallet',
    accountName: 'Indian Bank',
    accountNumber: '46669496496',
    transactionId: '005002',
    payAmount: '500 USD',
    paymentDay: '03-02-2025',
    status: 'spam',
    id: 'P0001',
    paymentMethod: 'UK Bank',
    acocuntHolderName: 'MR Jack',
    transactionReceipt: '',
    additionalNote: '',
    Currency: 'USD',
    Name: 'MR Jack'
  }
]

export const WithdrawData: IWithdraw[] = [
  {
    sl: 1,
    withdrawId: 'REF001',
    projectName: 'Web Dev',
    withdrawMethod: 'Bank',
    accountName: 'John Doe',
    accountNumber: '045001',
    withdrawAmount: 500,
    withdrawDay: '2024-04-19',
    status: 'Ineligible'
  },
  {
    sl: 2,
    withdrawId: 'REF002',
    projectName: 'App Dev',
    withdrawMethod: 'Bank',
    accountName: 'Jane Smith',
    accountNumber: '005002',
    withdrawAmount: 800,
    withdrawDay: '2024-04-20',
    status: 'Pending'
  },
  {
    sl: 3,
    withdrawId: 'REF003',
    projectName: 'Web Dev',
    withdrawMethod: 'Bank Wallet',
    accountName: 'Michael Johnson',
    accountNumber: '005002',
    withdrawAmount: 1000,
    withdrawDay: '2024-04-21',
    status: 'Sending'
  },
  {
    sl: 4,
    withdrawId: 'REF004',
    projectName: 'App Dev',
    withdrawMethod: 'Bank',
    accountName: 'Emily Brown',
    accountNumber: '005402',
    withdrawAmount: 700,
    withdrawDay: '2024-04-22',
    status: 'Pending'
  },
  {
    sl: 5,
    withdrawId: 'REF005',
    projectName: 'Web Dev',
    withdrawMethod: 'Bank Wallet',
    accountName: 'Daniel Wilson',
    accountNumber: '005402',
    withdrawAmount: 600,
    withdrawDay: '2024-04-23',
    status: 'Ineligible'
  },
  {
    sl: 6,
    withdrawId: 'REF006',
    projectName: 'Web Dev',
    withdrawMethod: 'Bank Wallet',
    accountName: 'Olivia Taylor',
    accountNumber: '045001',
    withdrawAmount: 900,
    withdrawDay: '2024-04-24',
    status: 'Sending'
  },
  {
    sl: 7,
    withdrawId: 'REF007',
    projectName: 'App Dev',
    withdrawMethod: 'Bank',
    accountName: 'Sophia Martinez',
    accountNumber: '005400',
    withdrawAmount: 1200,
    withdrawDay: '2024-04-25',
    status: 'Pending'
  }
]
