
interface countriesData {
    country:string;
    currency:string;
    isoCode:string;
}
const CurrencyData:countriesData[] = [
    { country: '00', currency: 'Afghani', isoCode: 'AFN' },
    { country: '001', currency: 'Afghani', isoCode: 'AFN' },
    { country: '002', currency: 'Lek', isoCode: 'ALL' },
    { country: '003', currency: 'Algerian Dinar', isoCode: 'DZD' },
    { country: '004', currency: 'US Dollar', isoCode: 'USD' },
    { country: '005', currency: 'Euro', isoCode: 'EUR' },
    { country: '006', currency: 'Kwanza', isoCode: 'AOA' },
    { country: '007', currency: 'East Caribbean Dollar', isoCode: 'XCD' },
    { country: '008', currency: 'East Caribbean Dollar', isoCode: 'XCD' },
    { country: '009', currency: 'Argentine Peso', isoCode: 'ARS' },
    { country: '010', currency: 'Armenian Dram', isoCode: 'AMD' },
    { country: '011', currency: 'Aruban Florin', isoCode: 'AWG' },
    { country: '012', currency: 'Australian Dollar', isoCode: 'AUD' },
    { country: '013', currency: 'Euro', isoCode: 'EUR' },
    { country: '014', currency: 'Azerbaijani Manat', isoCode: 'AZN' },
    { country: '015', currency: 'Bahamian Dollar', isoCode: 'BSD' },
    { country: '016', currency: 'Bahraini Dinar', isoCode: 'BHD' },
    { country: '017', currency: 'Taka', isoCode: 'BDT' },
    { country: '018', currency: 'Barbados Dollar', isoCode: 'BBD' },
    { country: '019', currency: 'Belarusian Ruble', isoCode: 'BYN' },
    { country: '020', currency: 'Euro', isoCode: 'EUR' },
    { country: '021', currency: 'Belize Dollar', isoCode: 'BZD' },
    { country: '022', currency: 'CFA Franc (BCEAO)', isoCode: 'XOF' },
    { country: '023', currency: 'Bermudian Dollar', isoCode: 'BMD' },
    { country: '024', currency: 'Ngultrum', isoCode: 'BTN' },
    { country: '025', currency: 'Boliviano', isoCode: 'BOB' },
    { country: '026', currency: 'US Dollar', isoCode: 'USD' },
    { country: '027', currency: 'Convertible Mark', isoCode: 'BAM' },
    { country: '028', currency: 'Pula', isoCode: 'BWP' },
    { country: '029', currency: 'Brazilian Real', isoCode: 'BRL' },
    { country: '030', currency: 'US Dollar', isoCode: 'USD' },
    { country: '031', currency: 'US Dollar', isoCode: 'USD' },
    { country: '032', currency: 'Brunei Dollar', isoCode: 'BND' },
    { country: '033', currency: 'Bulgarian Lev', isoCode: 'BGN' },
    { country: '034', currency: 'CFA Franc (BCEAO)', isoCode: 'XOF' },
    { country: '035', currency: 'Burundi Franc', isoCode: 'BIF' },
    { country: '036', currency: 'Cabo Verde Escudo', isoCode: 'CVE' },
    { country: '037', currency: 'Riel', isoCode: 'KHR' },
    { country: '038', currency: 'CFA Franc (BEAC)', isoCode: 'XAF' },
    { country: '039', currency: 'Canadian Dollar', isoCode: 'CAD' },
    { country: '040', currency: 'Cayman Islands Dollar', isoCode: 'KYD' },
    { country: '041', currency: 'CFA Franc (BEAC)', isoCode: 'XAF' },
    { country: '042', currency: 'CFA Franc (BEAC)', isoCode: 'XAF' },
    { country: '043', currency: 'Pound Sterling', isoCode: 'GBP' },
    { country: '044', currency: 'Chilean Peso', isoCode: 'CLP' },
    { country: '045', currency: 'Yuan Renminbi', isoCode: 'CNY' },
    { country: '046', currency: 'Hong Kong Dollar', isoCode: 'HKD' },
    { country: '047', currency: 'Pataca', isoCode: 'MOP' },
    { country: '048', currency: 'New Taiwan Dollar', isoCode: 'TWD' },
    { country: '049', currency: 'Australian Dollar', isoCode: 'AUD' },
    { country: '050', currency: 'Australian Dollar', isoCode: 'AUD' },
    { country: '051', currency: 'Colombian Peso', isoCode: 'COP' },
    { country: '052', currency: 'Comoro Franc', isoCode: 'KMF' },
    { country: '053', currency: 'CFA Franc (BEAC)', isoCode: 'XAF' },
    { country: '054', currency: 'Congolese Franc', isoCode: 'CDF' },
    { country: '055', currency: 'New Zealand Dollar', isoCode: 'NZD' },
    { country: '056', currency: 'Costa Rican Colón', isoCode: 'CRC' },
    { country: '057', currency: 'CFA Franc (BCEAO)', isoCode: 'XOF' },
    { country: '060', currency: 'Croatian Kuna', isoCode: 'HRK' },
    { country: '061', currency: 'Cuban Peso', isoCode: 'CUP' },
    { country: '062', currency: 'Netherlands Antillian Guilder', isoCode: 'ANG' },
    { country: '063', currency: 'Euro', isoCode: 'EUR' },
    { country: '064', currency: 'Czech Koruna', isoCode: 'CZK' },
    { country: '065', currency: 'Danish Krone', isoCode: 'DKK' },
    { country: '066', currency: 'Djibouti Franc', isoCode: 'DJF' },
    { country: '067', currency: 'East Caribbean Dollar', isoCode: 'XCD' },
    { country: '068', currency: 'Dominican Peso', isoCode: 'DOP' },
    { country: '069', currency: 'US Dollar', isoCode: 'USD' },
    { country: '070', currency: 'Egyptian Pound', isoCode: 'EGP' },
    { country: '071', currency: 'US Dollar', isoCode: 'USD' },
    { country: '072', currency: 'CFA Franc (BEAC)', isoCode: 'XAF' },
    { country: '073', currency: 'Nakfa', isoCode: 'ERN' },
    { country: '074', currency: 'Euro', isoCode: 'EUR' },
    { country: '075', currency: 'Ethiopian Birr', isoCode: 'ETB' },
    { country: '076', currency: 'Falkland Islands Pound', isoCode: 'FKP' },
    { country: '077', currency: 'Danish Krone', isoCode: 'DKK' },
    { country: '078', currency: 'Fiji Dollar', isoCode: 'FJD' },
    { country: '079', currency: 'Euro', isoCode: 'EUR' },
    { country: '080', currency: 'Euro', isoCode: 'EUR' },
    { country: '081', currency: 'Euro', isoCode: 'EUR' },
    { country: '082', currency: 'CFP Franc', isoCode: 'XPF' },
    { country: '083', currency: 'Euro', isoCode: 'EUR' },
    { country: '084', currency: 'CFA Franc (BEAC)', isoCode: 'XAF' },
    { country: '085', currency: 'Dalasi', isoCode: 'GMD' },
    { country: '086', currency: 'Lari', isoCode: 'GEL' },
    { country: '087', currency: 'Euro', isoCode: 'EUR' },
    { country: '088', currency: 'Ghana Cedi', isoCode: 'GHS' },
    { country: '089', currency: 'Gibraltar Pound', isoCode: 'GIP' },
    { country: '090', currency: 'Euro', isoCode: 'EUR' },
    { country: '091', currency: 'Danish Krone', isoCode: 'DKK' },
    { country: '092', currency: 'East Caribbean Dollar', isoCode: 'XCD' },
    { country: '093', currency: 'Euro', isoCode: 'EUR' },
    { country: '094', currency: 'US Dollar', isoCode: 'USD' },
    { country: '095', currency: 'Quetzal', isoCode: 'GTQ' },
    { country: '096', currency: 'Pound Sterling', isoCode: 'GBP' },
    { country: '097', currency: 'Guinea Franc', isoCode: 'GNF' },
    { country: '098', currency: 'CFA Franc (BCEAO)', isoCode: 'XOF' },
    { country: '099', currency: 'Guyana Dollar', isoCode: 'GYD' },
    { country: '100', currency: 'Gourde', isoCode: 'HTG' },
    { country: '101', currency: 'Lempira', isoCode: 'HNL' },
    { country: '102', currency: 'Forint', isoCode: 'HUF' },
    { country: '103', currency: 'Iceland Króna', isoCode: 'ISK' },
    { country: '104', currency: 'Indian Rupee', isoCode: 'INR' },
    { country: '105', currency: 'Rupiah', isoCode: 'IDR' },
    { country: '106', currency: 'Iranian Rial', isoCode: 'IRR' },
    { country: '107', currency: 'Iraqi Dinar', isoCode: 'IQD' },
    { country: '108', currency: 'Euro', isoCode: 'EUR' },
    { country: '109', currency: 'Pound Sterling', isoCode: 'GBP' },
    { country: '110', currency: 'New Israeli Sheqel', isoCode: 'ILS' },
    { country: '111', currency: 'Euro', isoCode: 'EUR' },
    { country: '112', currency: 'Jamaican Dollar', isoCode: 'JMD' },
    { country: '113', currency: 'Yen', isoCode: 'JPY' },
    { country: '114', currency: 'Pound Sterling', isoCode: 'GBP' },
    { country: '115', currency: 'Jordanian Dinar', isoCode: 'JOD' },
    { country: '116', currency: 'Tenge', isoCode: 'KZT' },
    { country: '117', currency: 'Kenyan Shilling', isoCode: 'KES' },
    { country: '118', currency: 'Australian Dollar', isoCode: 'AUD' },
    { country: '119', currency: 'North Korean Won', isoCode: 'KPW' },
    { country: '120', currency: 'Won', isoCode: 'KRW' },
    { country: '121', currency: 'Kuwaiti Dinar', isoCode: 'KWD' },
    { country: '122', currency: 'Som', isoCode: 'KGS' },
    { country: '123', currency: 'Kip', isoCode: 'LAK' },
    { country: '124', currency: 'Euro', isoCode: 'EUR' },
    { country: '125', currency: 'Lebanese Pound', isoCode: 'LBP' },
    { country: '126', currency: 'Loti', isoCode: 'LSL' },
    { country: '127', currency: 'Liberian Dollar', isoCode: 'LRD' },
    { country: '128', currency: 'Libyan Dinar', isoCode: 'LYD' },
    { country: '129', currency: 'Swiss Franc', isoCode: 'CHF' },
    { country: '130', currency: 'Euro', isoCode: 'EUR' },
    { country: '131', currency: 'Euro', isoCode: 'EUR' },
    { country: '132', currency: 'Denar', isoCode: 'MKD' },
    { country: '133', currency: 'Malagasy Ariary', isoCode: 'MGA' },
    { country: '134', currency: 'Malawi Kwacha', isoCode: 'MWK' },
    { country: '135', currency: 'Malaysian Ringgit', isoCode: 'MYR' },
    { country: '136', currency: 'Rufiyaa', isoCode: 'MVR' },
    { country: '137', currency: 'CFA Franc (BCEAO)', isoCode: 'XOF' },
    { country: '138', currency: 'Euro', isoCode: 'EUR' },
    { country: '139', currency: 'US Dollar', isoCode: 'USD' },
    { country: '140', currency: 'Euro', isoCode: 'EUR' },
    { country: '141', currency: 'Ouguiya', isoCode: 'MRO' },
    { country: '142', currency: 'Mauritius Rupee', isoCode: 'MUR' },
    { country: '143', currency: 'Euro', isoCode: 'EUR' },
    { country: '144', currency: 'Mexican Peso', isoCode: 'MXN' },
    { country: '145', currency: 'US Dollar', isoCode: 'USD' },
    { country: '146', currency: 'Moldovan Leu', isoCode: 'MDL' },
    { country: '147', currency: 'Tugrik', isoCode: 'MNT' },
    { country: '148', currency: 'Euro', isoCode: 'EUR' },
    { country: '149', currency: 'East Caribbean Dollar', isoCode: 'XCD' },
    { country: '150', currency: 'Moroccan Dirham', isoCode: 'MAD' },
    { country: '151', currency: 'Metical', isoCode: 'MZN' },
    { country: '152', currency: 'Kyat', isoCode: 'MMK' },
    { country: '153', currency: 'Namibian Dollar', isoCode: 'NAD' },
    { country: '154', currency: 'Australian Dollar', isoCode: 'AUD' },
    { country: '155', currency: 'Nepalese Rupee', isoCode: 'NPR' },
    { country: '156', currency: 'Euro', isoCode: 'EUR' },
    { country: '157', currency: 'CFP Franc', isoCode: 'XPF' },
    { country: '158', currency: 'CFP Franc', isoCode: 'XPF' },
    { country: '159', currency: 'New Zealand Dollar', isoCode: 'NZD' },
    { country: '160', currency: 'Córdoba Oro', isoCode: 'NIO' },
    { country: '161', currency: 'CFA Franc (BCEAO)', isoCode: 'XOF' },
    { country: '162', currency: 'Naira', isoCode: 'NGN' },
    { country: '163', currency: 'New Zealand Dollar', isoCode: 'NZD' },
    { country: '164', currency: 'US Dollar', isoCode: 'USD' },
    { country: '165', currency: 'Norwegian Krone', isoCode: 'NOK' },
    { country: '166', currency: 'Rial Omani', isoCode: 'OMR' },
    { country: '167', currency: 'Pakistan Rupee', isoCode: 'PKR' },
    { country: '168', currency: 'US Dollar', isoCode: 'USD' },
    { country: '169', currency: 'Balboa', isoCode: 'PAB' },
    { country: '170', currency: 'Kina', isoCode: 'PGK' },
    { country: '171', currency: 'Guaraní', isoCode: 'PYG' },
    { country: '172', currency: 'Sol', isoCode: 'PEN' },
    { country: '173', currency: 'Philippine Peso', isoCode: 'PHP' },
    { country: '174', currency: 'New Zealand Dollar', isoCode: 'NZD' },
    { country: '175', currency: 'Zloty', isoCode: 'PLN' },
    { country: '176', currency: 'Euro', isoCode: 'EUR' },
    { country: '177', currency: 'US Dollar', isoCode: 'USD' },
    { country: '178', currency: 'Qatari Rial', isoCode: 'QAR' },
    { country: '179', currency: 'Euro', isoCode: 'EUR' },
    { country: '180', currency: 'Romanian Leu', isoCode: 'RON' },
    { country: '181', currency: 'Russian Ruble', isoCode: 'RUB' },
    { country: '182', currency: 'Rwanda Franc', isoCode: 'RWF' },
    { country: '183', currency: 'Euro', isoCode: 'EUR' },
    { country: '184', currency: 'Saint Helena Pound', isoCode: 'SHP' },
    { country: '185', currency: 'East Caribbean Dollar', isoCode: 'XCD' },
    { country: '186', currency: 'East Caribbean Dollar', isoCode: 'XCD' },
    { country: '187', currency: 'Euro', isoCode: 'EUR' },
    { country: '188', currency: 'Euro', isoCode: 'EUR' },
    { country: '189', currency: 'Euro', isoCode: 'EUR' },
    { country: '190', currency: 'Euro', isoCode: 'EUR' },
    { country: '191', currency: 'Tala', isoCode: 'WST' },
    { country: '192', currency: 'Dobra', isoCode: 'STD' },
    { country: '193', currency: 'Saudi Riyal', isoCode: 'SAR' },
    { country: '194', currency: 'CFA Franc (BCEAO)', isoCode: 'XOF' },
    { country: '195', currency: 'Serbian Dinar', isoCode: 'RSD' },
    { country: '196', currency: 'Seychelles Rupee', isoCode: 'SCR' },
    { country: '197', currency: 'Leone', isoCode: 'SLL' },
    { country: '198', currency: 'Singapore Dollar', isoCode: 'SGD' },
    { country: '199', currency: 'Netherlands Antillian Guilder', isoCode: 'ANG' },
    { country: '200', currency: 'Euro', isoCode: 'EUR' },
    { country: '201', currency: 'Euro', isoCode: 'EUR' },
    { country: '202', currency: 'Solomon Islands Dollar', isoCode: 'SBD' },
    { country: '203', currency: 'Somali Shilling', isoCode: 'SOS' },
    { country: '204', currency: 'Rand', isoCode: 'ZAR' },
    { country: '205', currency: 'South Sudanese Pound', isoCode: 'SSP' },
    { country: '206', currency: 'Euro', isoCode: 'EUR' },
    { country: '207', currency: 'Sri Lanka Rupee', isoCode: 'LKR' },
    { country: '208', currency: 'Sudanese Pound', isoCode: 'SDG' },
    { country: '209', currency: 'Suriname Dollar', isoCode: 'SRD' },
    { country: '210', currency: 'Lilangeni', isoCode: 'SZL' },
    { country: '211', currency: 'Swedish Krona', isoCode: 'SEK' },
    { country: '212', currency: 'Swiss Franc', isoCode: 'CHF' },
    { country: '213', currency: 'Syrian Pound', isoCode: 'SYP' },
    { country: '214', currency: 'Somoni', isoCode: 'TJS' },
    { country: '215', currency: 'Tanzanian Shilling', isoCode: 'TZS' },
    { country: '216', currency: 'Baht', isoCode: 'THB' },
    { country: '217', currency: 'US Dollar', isoCode: 'USD' },
    { country: '218', currency: 'CFA Franc (BCEAO)', isoCode: 'XOF' },
    { country: '219', currency: 'New Zealand Dollar', isoCode: 'NZD' },
    { country: '220', currency: 'Pa\'anga', isoCode: 'TOP' },
    { country: '221', currency: 'Trinidad and Tobago Dollar', isoCode: 'TTD' },
    { country: '222', currency: 'Tunisian Dinar', isoCode: 'TND' },
    { country: '223', currency: 'Turkish Lira', isoCode: 'TRY' },
    { country: '224', currency: 'Turkmenistan New Manat', isoCode: 'TMT' },
    { country: '225', currency: 'US Dollar', isoCode: 'USD' },
    { country: '226', currency: 'Australian Dollar', isoCode: 'AUD' },
    { country: '227', currency: 'Uganda Shilling', isoCode: 'UGX' },
    { country: '228', currency: 'Hryvnia', isoCode: 'UAH' },
    { country: '229', currency: 'UAE Dirham', isoCode: 'AED' },
    { country: '230', currency: 'Pound Sterling', isoCode: 'GBP' },
    { country: '231', currency: 'US Dollar', isoCode: 'USD' },
    { country: '232', currency: 'US Dollar', isoCode: 'USD' },
    { country: '233', currency: 'Peso Uruguayo', isoCode: 'UYU' },
    { country: '234', currency: 'Uzbekistan Sum', isoCode: 'UZS' },
    { country: '235', currency: 'Vatu', isoCode: 'VUV' },
    { country: '236', currency: 'Bolívar', isoCode: 'VEF' },
    { country: '237', currency: 'Dong', isoCode: 'VND' },
    { country: '238', currency: 'CFP Franc', isoCode: 'XPF' },
    { country: '239', currency: 'Moroccan Dirham', isoCode: 'MAD' },
    { country: '240', currency: 'Yemeni Rial', isoCode: 'YER' },
    { country: '241', currency: 'Zambian Kwacha', isoCode: 'ZMW' },
    { country: '242', currency: 'Zimbabwe Dollar', isoCode: 'ZWL' } ]
  
  
  export default CurrencyData;
  